#!/bin/sh

unset FAILSAFE
[ -e /tmp/.failsafe ] && export FAILSAFE=1

[ -f /etc/banner ] && cat /etc/banner
[ -n "$FAILSAFE" ] && [ -f /etc/banner.failsafe ] && cat /etc/banner.failsafe

export PATH="/usr/sbin:/usr/bin:/sbin:/bin"
HOME="$(grep -E "^${USER:-root}:" /etc/passwd | cut -d: -f6)"
HOME="${HOME:-/root}"
export HOME
export PS1='\u@\h:\w\$ '
export ENV=/etc/shinit

if [ -z "$FAILSAFE" ]; then
	for FILE in /etc/profile.d/*.sh; do
		[ -f "${FILE%.sh}.hush" ] && continue
		[ -f "$FILE" ] && . "$FILE"
	done
	unset FILE
fi
